<?php

/* Copyright (c) 1998-2009 ILIAS open source, Extended GPL, see https://github.com/ILIAS-eLearning/ILIAS/tree/trunk/docs/LICENSE */

/**
 * Generated by srag\PluginGenerator v0.9.9
 *
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author studer + raimann ag - Team Custom 1 <ms@studer-raimann.ch>
 */

require_once __DIR__ . "/vendor/srag/dic/src/PHPVersionChecker.php";

$id = "srdtv";
$version = "0.1.0";
$ilias_min_version = "5.3.0";
$ilias_max_version = "5.3.999";
$responsible = "studer + raimann ag - Team Custom 1";
$responsible_mail = "ms@studer-raimann.ch";
