<?php

/* Copyright (c) 1998-2009 ILIAS open source, Extended GPL, see https://github.com/ILIAS-eLearning/ILIAS/tree/trunk/docs/LICENSE */

require_once __DIR__ . "/../../vendor/autoload.php";

use srag\Plugins\SrDclTableView\Utils\SrDclTableViewTrait;
use srag\RemovePluginDataConfirm\SrDclTableView\AbstractRemovePluginDataConfirm;

/**
 * Class SrDclTableViewRemoveDataConfirm
 *
 * Generated by srag\PluginGenerator v0.9.9
 *
 * @author            studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author            studer + raimann ag - Team Custom 1 <ms@studer-raimann.ch>
 *
 * @ilCtrl_isCalledBy SrDclTableViewRemoveDataConfirm: ilUIPluginRouterGUI
 */
class SrDclTableViewRemoveDataConfirm extends AbstractRemovePluginDataConfirm {

	use SrDclTableViewTrait;
	const PLUGIN_CLASS_NAME = ilSrDclTableViewPlugin::class;
}
