<#1>
<?php
/**
 * Copyright (c) 1998-2009 ILIAS open source, Extended GPL, see https://github.com/ILIAS-eLearning/ILIAS/tree/trunk/docs/LICENSE
 *
 * Generated by srag\PluginGenerator v0.9.9
 *
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author studer + raimann ag - Team Custom 1 <ms@studer-raimann.ch>
 */
?>
<#2>
<?php
srag\Plugins\SrDclTableView\Config\Config::updateDB();
?>
<#3>
<?php
srag\Plugins\SrDclTableView\Config\Config::updateDB();
?>
<#4>
<?php
srag\Plugins\SrDclTableView\Config\Config::updateDB();
?>
<#5>
<?php
srag\Plugins\SrDclTableView\Config\Config::updateDB();
?>
<#6>
<?php
srag\Plugins\SrDclTableView\Config\Config::updateDB();
?>
<#7>
<?php
srag\Plugins\SrDclTableView\Config\Config::updateDB();
?>
<#8>
<?php
srag\Plugins\SrDclTableView\Config\Config::updateDB();
?>
<#9>
<?php
srag\Plugins\SrDclTableView\Config\Config::updateDB();
?>